config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks, only: [:create, :update]
  end

  root "projects#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  enum status: { open: 0, in_progress: 1, done: 2 }

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects
  end

  def show
    @project = current_user.projects.find(params[:id])
  end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project

  def create
    @task = @project.tasks.new(task_params)

    if @task.save
      redirect_to @project
    else
      render "projects/show"
    end
  end

  def update
    @task = @project.tasks.find(params[:id])
    @task.update(task_params)
    redirect_to @project
  end

  private

  def set_project
    @project = current_user.projects.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:title, :status)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <% if user_signed_in? %>
      Logged in as <%= current_user.email %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1>My Projects</h1>

<%= link_to "New Project", new_project_path %>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.name, project %>
    </li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_with model: @project do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>
  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>

<h3>Tasks</h3>

<ul>
  <% @project.tasks.each do |task| %>
    <li>
      <%= task.title %> — <%= task.status %>

      <%= form_with model: [@project, task], method: :patch do |f| %>
        <%= f.select :status, Task.statuses.keys %>
        <%= f.submit "Update" %>
      <% end %>
    </li>
  <% end %>
</ul>

<h3>Add Task</h3>
<%= render "tasks/form", project: @project, task: Task.new %>

app/views/tasks/_form.html.erb
<%= form_with model: [project, task] do |f| %>
  <%= f.text_field :title %>
  <%= f.select :status, Task.statuses.keys %>
  <%= f.submit %>
<% end %>